//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FXtradeTable
    {
        public int Id { get; set; }
        public int SummaryId { get; set; }
        public string CurrencyClass { get; set; }
        public Nullable<double> NTD { get; set; }
        public Nullable<double> USD { get; set; }
        public Nullable<double> ExchargeRate { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<System.DateTime> Tradetime { get; set; }
        public string TradeClass { get; set; }
        public string note { get; set; }
    
        public virtual SummaryTable SummaryTable { get; set; }
    }
}
