//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurances
    {
        public int SerialNumber { get; set; }
        public Nullable<int> STID { get; set; }
        public string UserID { get; set; }
        public string InsuranceName { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime WithdrawDate { get; set; }
        public Nullable<int> PaymentPerYear { get; set; }
        public Nullable<int> PayYear { get; set; }
        public Nullable<bool> PurchaseOrWithdraw { get; set; }
        public Nullable<int> Withdrawal { get; set; }
        public Nullable<bool> Withdrawed { get; set; }
        public Nullable<int> CashFlow { get; set; }
        public bool RelateCash { get; set; }
    
        public virtual SummaryTable SummaryTable { get; set; }
        public virtual UsersData UsersData { get; set; }
    }
}
