//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1005.Areas.ForeignExchange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeTable
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string MClass { get; set; }
        public Nullable<double> NTD { get; set; }
        public Nullable<double> USD { get; set; }
        public Nullable<double> FX { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<System.DateTime> Ttime { get; set; }
        public string TClass { get; set; }
    }
}
